# Generated by Django 4.2 on 2025-08-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("patient_data", models.JSONField()),
                ("supplements", models.JSONField()),
                ("recommendations", models.JSONField()),
                ("report_html", models.TextField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
